### ISSUE TITLE
Sugestion

### ISSUE THREAD

**Issue by Natmusknud** [bobthebutcher/ise#4]
Is it possible to get a function there can update description for an endpointwiyhout deleting it and create it again

**Comment by bwks** [comment]
Thank you for reaching out. It may be but I could not say for sure. I have not worked with ISE for a number of years and do not have any means to test at present. If you would like to raise a PR. I will help to review and get it merged. 

FYI I will probably archive this repo since I am no longer maintaining it. Fee free to fork it.

**Comment by bwks** [comment]
Closing this issue as I will be archiving the project.
